main : main.o cony.o brown.o dfs.o
	gcc -g -o main main.o cony.o brown.o dfs.o
main.o : main.c
	gcc -g -c main.c
cony.o : cony.c
	gcc -g -c cony.c
brown.o : brown.c
	gcc -g -c brown.c
dfs.o : dfs.c
	gcc -g -c dfs.c

