main : main.o tree.o min.o delnode.o newnode.o mindepth.o
	gcc -g -o main main.o tree.o min.o delnode.o newnode.o mindepth.o
main.o : main.c
	gcc -g -c main.c
tree.o : tree.c
	gcc -g -c tree.c
min.o : min.c
	gcc -g -c min.c
newnode.o : newnode.c
	gcc -g -c newnode.c
delnode.o : delnode.c
	gcc -g -c delnode.c
mindepth.o : mindepth.c
	gcc -g -c mindepth.c

